#!/bin/bash

DIR="$(cd "$(dirname "$0")/.." && pwd)"
BIN=$DIR/node_modules/.bin

export NPM_CONFIG_PREFIX="${NPM_CONFIG_PREFIX:-$DIR/prefix}"
export NPM_CONFIG_CACHE="${NPM_CONFIG_CACHE:-$DIR/cache}"

$BIN/node $BIN/npx "$@"